name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
categories:
  - title: "Features"
    labels:
      - "feat"
      - "feature"
      - "enhancement"
  - title: "**BREAKING**"
    labels:
      - "breaking"
  - title: "Fixes"
    labels:
      - "fix"
      - "bugfix"
      - "bug"
  - title: "Documentation"
    labels:
      - "documentation"
  - title: "Testing"
    labels:
      - "test"
  - title: "Maintenance / Dependencies"
    labels:
      - "chore"
  - title: "Dependabot"
    labels:
      - "dependencies"

change-template: |
  <details>
  <summary>$TITLE (#$NUMBER)</summary>

  ### $TITLE (#$NUMBER)

  $BODY

  ---

  </details>

change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
version-resolver:
  major:
    labels:
      - major
      - breaking
  minor:
    labels:
      - minor
      - feature
  patch:
    labels:
      - patch
      - chore
      - fix
      - documentation
  default: patch
exclude-labels:
  - "exclude"
autolabeler:
  - label: "chore"
    title:
      - "/chore/i"
      - "/^ci[:](?! Workflow Bot)/i"
      - "/ci: Workflow Bot/i"
  - label: "documentation"
    files:
      - "/docs/**/*.md"
    title:
      - "/docs?/i"
  - label: "fix"
    title:
      - "/fix/i"
      - "/dev:/i"
      - "/refactor/i"
  - label: "feature"
    title:
      - "/^feat/i"
  - label: "test"
    title:
      - "/^test/i"
  - label: "breaking"
    title:
      - "/^fix[!]/i"
      - "/^feat[!]/i"

template: |
  ## Changes

  $CHANGES

# cspell:ignore autolabeler
