name: setup_node
description: Setup Node, and install Npm
inputs:
  node-version:
    required: false
    description: The version of Node to use.
    default: '22.x'
runs:
  using: 'composite'
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@48b55a011bda9f5d6aeb4c2d9c7362e8dae4041e # v6
      with:
        registry-url: 'https://registry.npmjs.org'
        node-version: ${{ inputs.node-version }}
        cache: 'npm'
    - name: NPM Version
      run: npm -v;
      shell: bash
