name: cspell-action
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v5
      - uses: streetsidesoftware/cspell-action@v9
        with:
          files: '.'
          incremental_files_only: false
          check_dot_files: true
