name: cspell-action
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v5
      - uses: streetsidesoftware/cspell-action@v8
        with:
          files: '.'
          incremental_files_only: false
          check_dot_files: true
