name: cspell-action
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v5
      - uses: streetsidesoftware/cspell-action@v8
        with:
          files: '.'
          incremental_files_only: false
          check_dot_files: true
